-- Script generated by Redgate Compare v1.12.2.9897
SET check_function_bodies = false;


DO language plpgsql $$BEGIN RAISE NOTICE 'Altering carrier.product_id_seq...';END$$;
ALTER SEQUENCE carrier.product_id_seq OWNED BY NONE;


DO language plpgsql $$BEGIN RAISE NOTICE 'Dropping carrier.product...';END$$;
DROP TABLE carrier.product;


DO language plpgsql $$BEGIN RAISE NOTICE 'Dropping carrier.product_id_seq...';END$$;
DROP SEQUENCE carrier.product_id_seq;

SET check_function_bodies = true;
